@DotnetAgents.Agent_HostAddress = http://localhost:5113

GET {{DotnetAgents.Agent_HostAddress}}/todos/
Accept: application/json

###

GET {{DotnetAgents.Agent_HostAddress}}/todos/1
Accept: application/json

###
